### ISSUE TITLE
UnhandledRejection: Navigation timeout of 30000 ms exceeded

### ISSUE THREAD

**Issue by denidarmayana** [wppconnect-team/wppconnect-php-client#2]
at /home/darma/wppconnect-server/node_modules/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:106:111
    at async FrameManager.navigateFrame (/home/darma/wppconnect-server/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:91:21)
    at async Frame.goto (/home/darma/wppconnect-server/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:417:16)
    at async Page.goto (/home/darma/wppconnect-server/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1156:16)

how to solve this

**Comment by bgastaldi** [comment]
This same issue in server repository.
